# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
